# Cheatsheet de Numpy 

La librería Numpy se utiliza en diversas áreas para cómputo científico, dado que es de fácil manejo para trabajos que utilicen arreglos multidimensionales

## Importación de la biblioteca
Por conveniencia de define esta librería como np

In [1]:
import numpy as np

## Creación de arreglos
Numpy nos permite trabajar con arreglos de uno, dos o hasta tres dimensiones

In [2]:
#Arreglo 1D
a = np.array([1,2,3])
a

array([1, 2, 3])

In [3]:
#Arreglo 2D
b = np.array([(1.5,2,3),(4,5,6)], dtype = float)
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [4]:
#Arreglo 3D
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]], dtype = float)
c

array([[[1.5, 2. , 3. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 1. ],
        [4. , 5. , 6. ]]])

### Funciones para crear arreglos especiales

In [5]:
np.zeros((3,4))  #Esta función crea un arreglo 2D de ceros, de 3x4

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [6]:
np.ones((2,3,4), dtype = int)  #Creación de un arreglo 3D de unos con dimensión 2x3x4

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]])

### Arreglos con valores espaciados

In [7]:
d = np.arange(18, 25, 5) #La función arange con argumentos (a, b, c) crea un arreglo con valores espaciados de a-b con espaciamiento c
d

array([18, 23])

In [8]:
np.linspace(8, 2, 9) #La función linspace con argumentos (a, b, c) crea un arreglo con valores de a-b con una longitud de c


array([8.  , 7.25, 6.5 , 5.75, 5.  , 4.25, 3.5 , 2.75, 2.  ])

### También es posible utilizar las siguientes funciones para crear otro tipo de arreglos:
- np.full((A, B), C) &ensp; &ensp; &ensp; &ensp; &ensp; &ensp; &ensp;  &ensp; &nbsp;*En esta función creamos un arreglo constante de dimensiones AxB con valores C* 
- np.eye(A)  &emsp;  &emsp;  &emsp;  &emsp; &emsp; &emsp; &emsp; *Esta función crea una matriz identidad de dimensión AxA*
- np.random.random((A,B)) &ensp; &ensp; *Creación de una matriz de dimensión AxB con valores aleatorios*
- np.empty((A,B)) &emsp;  &emsp; &emsp;  &emsp;   &ensp; *Creación de un espacio en forma de arreglo 2D con dimensiones AxB con valores nulo*

## Tipos de datos

- np.int64  &emsp;  &emsp;  &emsp; *Enteros representados en 64 bits*
- np.float32 &emsp;  &ensp;  &ensp; *Números con decimal*
- np.complex &emsp;  &ensp;   *Números complejos representados por 128 flotantes*
- np.bool    &emsp;  &emsp;  &emsp; *Valores booleanos que pueden ser TRUE o FALSE*
- np.object  &emsp;  &emsp; &nbsp;   *Objeto de Python*
- np.string_ &emsp;  &emsp;  &nbsp; *String de longitud fija*
- np.unicode_   &emsp;    &ensp; *Unicode de longitud fija*

## Inspección de arreglos

In [9]:
#Dimensión de arreglos
a.shape 

(3,)

In [10]:
#Longitud de un arreglo
len(a)

3

In [11]:
#Número de dimensiones de un arreglo
b.ndim

2

In [12]:
#Número de elementos en un arreglo
c.size

12

In [13]:
#Tipo de datos de los elementos de un arreglo
b.dtype

dtype('float64')

In [14]:
#Nombre del tipo de datos
b.dtype.name

'float64'

In [15]:
#Transformar tipo de datos de un arreglo 
a.astype(float)

array([1., 2., 3.])

## Matemáticas con arreglos

### Operaciones aritméticas 

In [16]:
#Resta convencional y resta con numpy

r1 = a-b 
print(r1)
np.subtract(a,b)

[[-0.5  0.   0. ]
 [-3.  -3.  -3. ]]


array([[-0.5,  0. ,  0. ],
       [-3. , -3. , -3. ]])

In [17]:
#Suma convencional y suma con numpy

s1 = a+b 
print(s1)
np.add(a,b)

[[2.5 4.  6. ]
 [5.  7.  9. ]]


array([[2.5, 4. , 6. ],
       [5. , 7. , 9. ]])

In [18]:
#División convencional y división con numpy

d1 = a/b 
print(d1)
np.divide(a,b)

[[0.66666667 1.         1.        ]
 [0.25       0.4        0.5       ]]


array([[0.66666667, 1.        , 1.        ],
       [0.25      , 0.4       , 0.5       ]])

In [19]:
#Multiplicación convencional y multiplicación con numpy

m1 = a*b 
print(m1)
np.multiply(a,b)

[[ 1.5  4.   9. ]
 [ 4.  10.  18. ]]


array([[ 1.5,  4. ,  9. ],
       [ 4. , 10. , 18. ]])

#### Algunas otras operaciones menos comúnes

- np.exp(A) &emsp; *Exponeciación* 
- np.sqrt(A) &emsp; *Raíz cuadrada*
- np.sin(A) &emsp; &nbsp; *Seno*
- np.cos(A) &emsp; *Coseno*
- np.log(A) &emsp; *Logaritmo natural*
- A.dot(B) &emsp; *Producto punto de A con B*

### Comparación 

In [20]:
a == b #Comparación elemento por elemento, regresa un arreglo booleano con dimensiones del arreglo más grande

array([[False,  True,  True],
       [False, False, False]])

In [21]:
a < 2 #Comparación de todos los elementos con un solo valor. Regresa un arreglo booleano con las dimensiones del arreglo que se compara

array([ True, False, False])

In [22]:
np.array_equal(a,b) #Comparación general de arreglo a con b. Regresa un valor booleano

False

### Funciones agregadas sobre un mismo arreglo

- a.sum() &emsp; &emsp; &emsp; &emsp; &emsp; *Suma de todos los elementos del arreglo* 
- a.min() &emsp; &emsp; &emsp; &emsp; &emsp; *Valor mínimo del arreglo*
- b.max(axis=0) &emsp; &emsp; &ensp; *Valor máximo de una fila del arreglo*
- b.cumsum(axis=1) &emsp; *Suma cumulativa de un arreglo de más de 1D*
- a.mean() &emsp; &emsp; &emsp; &emsp; *Valor promedio del arreglo*
- np.median(b) &emsp; &emsp; &ensp; *Mediana del arreglo*
- np.corrcoef(a) &emsp; &ensp; &emsp;*Coeficiente de correlación*
- np.std(b) &emsp; &emsp; &emsp; &emsp;*Desviación estándar*

## Copia de arreglos

In [23]:
#Crear una vista de un arreglo con los mismos datos
h1 = a.view()
h1

array([1, 2, 3])

In [24]:
#Crear una copia de un arreglo
np.copy(a)

array([1, 2, 3])

In [25]:
#Crear una copia profunda de un arreglo
h2 = a.copy()
h2

array([1, 2, 3])

## Ordenando arreglos 

In [26]:
#Ordenar de menor a mayor
a = np.array([2, 3, 1])
a.sort()
a

array([1, 2, 3])

In [27]:
#Ordenar los elementos de un arreglo tipo matriz
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]], dtype = float)
c.sort(axis=0)
c

array([[[1.5, 2. , 1. ],
        [4. , 5. , 6. ]],

       [[3. , 2. , 3. ],
        [4. , 5. , 6. ]]])

## Selección, cortes e índices

In [28]:
a = np.array([1,2,3])
b = np.array([(1.5,2,3),(4,5,6)], dtype = float)
c = np.array([[(1.5,2,3),(4,5,6)],[(3,2,1),(4,5,6)]], dtype = float)

#### Selección 

In [29]:
a[2] #Selección del tercer elemento del arreglo. Se cuenta desde el 0

3

In [30]:
b[1,2] #Selección del elemento en la fila 2 y columna 3

6.0

#### Cortes 

In [31]:
#Selección del elemento 1 al 2. El valor despues de : significa menor que
a[0:2]

array([1, 2])

In [32]:
#Selección de los elementos de la fila 1 a la 2 de la columna 2
b[0:2,1]

array([2., 5.])

In [33]:
b[:1] #Todos los elementos de la columna 0

array([[1.5, 2. , 3. ]])

In [34]:
#Todos los elementos del segundo termino de un arreglo 3D
c[1,:,:]

array([[3., 2., 1.],
       [4., 5., 6.]])

In [35]:
#Elementos en reversa. Los números negativos siempre van despues de :
a[:-1]

array([1, 2])

#### Index booleano 

In [36]:
#Seleccionar elementos con valor menor de 2
a[a<2]

array([1])

#### Otras formas de indexar 

In [37]:
#Seleccionar elementos (1,0), (0,1), (1,2) y (0,0)
b[[1, 0, 1, 0], [0, 1, 2, 0]]

array([4. , 2. , 6. , 1.5])

In [38]:
#Seleccionar un subconjunto de filas y columnas de la matriz
b[[1, 0, 1, 0]][:,[0, 1, 2, 0]]

array([[4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5],
       [4. , 5. , 6. , 4. ],
       [1.5, 2. , 3. , 1.5]])

## Manipulación de arreglos 

### Transponer elementos

In [39]:
#Permutar dimensiones de arreglo
i = np.transpose(b)
i

array([[1.5, 4. ],
       [2. , 5. ],
       [3. , 6. ]])

In [40]:
#Permutar dimensiones de arreglo
i.T

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

### Cambiar forma de arreglos

In [41]:
#Aplanar el arreglo
b.ravel()

array([1.5, 2. , 3. , 4. , 5. , 6. ])

In [42]:
#Cambiar forma pero no cambiar los datos
b.reshape(3,-2)

array([[1.5, 2. ],
       [3. , 4. ],
       [5. , 6. ]])

### Añadir o quitar elementos

In [43]:
#Concatenar el contenido de dos objetos en un arreglo
np.append(a,b)

array([1. , 2. , 3. , 1.5, 2. , 3. , 4. , 5. , 6. ])

In [44]:
#Insertar argumento en el arreglo A en la posicion 2+1 el valor 59
np.insert(a, 2, 59)

array([ 1,  2, 59,  3])

In [45]:
#Borrar del arreglo A, el valor en la posición 2+1 en adelante
np.delete(a,[2])

array([1, 2])

### Combinar arreglos

In [46]:
#Concatenar arreglos
np.concatenate((a,d),axis=0)

array([ 1,  2,  3, 18, 23])

In [47]:
#Apilar dos arreglos de forma vertical (sobre las filas)
np.vstack((a,b))

array([[1. , 2. , 3. ],
       [1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [48]:
#Otra forma de apilar de forma vertical
e = np.ones((2,3))
np.r_[b,e]

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ],
       [1. , 1. , 1. ],
       [1. , 1. , 1. ]])

In [49]:
#Apilamiento horizontal
np.hstack((b,e))

array([[1.5, 2. , 3. , 1. , 1. , 1. ],
       [4. , 5. , 6. , 1. , 1. , 1. ]])

In [50]:
#Apilamiento por columnas
np.column_stack((b,e))

array([[1.5, 2. , 3. , 1. , 1. , 1. ],
       [4. , 5. , 6. , 1. , 1. , 1. ]])

In [51]:
#Otra forma de apilar por columnas
np.c_[b,e]

array([[1.5, 2. , 3. , 1. , 1. , 1. ],
       [4. , 5. , 6. , 1. , 1. , 1. ]])

### Dividir arreglos

In [52]:
#Dividir el arreglo de forma horizontal en tres arreglos
np.hsplit(b,3)

[array([[1.5],
        [4. ]]),
 array([[2.],
        [5.]]),
 array([[3.],
        [6.]])]

In [53]:
#Dividir el arreglo de forma vertical en dos arreglos
np.vsplit(b,2)

[array([[1.5, 2. , 3. ]]), array([[4., 5., 6.]])]

## Guardar y cargar información

### Guardar y cargar en el disco

In [ ]:
np.save("mi_arreglo",a)
np.savez("arreglo.npz",a,b)
np.load("arreglo.npy")

### Guardar y cargar archivos de texto 

In [ ]:
np.loadtxt("miarchivo.txt")
np.genfromtxt("mi_archivo.csv",delimiter=",")
np.savetxt("miarreglo.txt",a,delimiter=" ")

## Pedir ayuda 

In [54]:
np.info(np.ndarray.dtype)

Data-type of the array's elements.

Parameters
----------
None

Returns
-------
d : numpy dtype object

See Also
--------
numpy.dtype

Examples
--------
>>> x
array([[0, 1],
       [2, 3]])
>>> x.dtype
dtype('int32')
>>> type(x.dtype)
<type 'numpy.dtype'>
